### PR TITLE
Fix compilation in latest Nim

### PR DESCRIPTION
**Pull request by dom96**
Brilliant job on this library by the way!

### CODE REVIEW

**Comment by CORDEA** [comment]
Thanks for pull request! Excellent work :)

Actually, support for the latest nim had done in the develop branch. 
https://github.com/CORDEA/oauth/blob/master/.travis/install.sh#L21-L25
I'm going to merge the develop branch into master immediately.

Please let me know if there are any problems.

**Comment by dom96** [comment]
Oh, didn't see that. Cool! Might be a good idea to mention it in the readme :)

**Comment by CORDEA** [comment]
You are right. I will do it ;)

**Comment by dom96** [comment]
Also, add it to the Nimble package list when you get a chance.

**Comment by CORDEA** [comment]
OK. Thanks for everything!

**Pull request closed without merging**
