### PR TITLE
fix oauth.nimble to work with latest nimble

### PR DESCRIPTION
**Pull request by timotheecour**
please update git tag after merging this

### CODE REVIEW

**Comment by dom96** [comment]
Does the current verison not work with latest Nimble? It should... or are you just updating to the latest format for future-proofing?

**Comment by timotheecour** [comment]
with my nimble version (nimble v0.9.0 compiled at 2019-01-14 11:56:17) I'm getting:
```
oauth.nimble(1, 2) Error: undeclared identifier: 'Package'
```

**Comment by dom96** [comment]
huh? What are you running? Can you show me the full output?

**Comment by CORDEA** [comment]
thank you for your help!

> with my nimble version (nimble v0.9.0 compiled at 2019-01-14 11:56:17) I'm getting:

Maybe I've never encountered 'undeclared identifier' error in the old format. Hmm...

**Comment by CORDEA** [comment]
released v0.8 :)

https://github.com/CORDEA/oauth/releases/tag/v0.8

**Pull request merged**
